<?php
function shiftcipher_menu(){
    $items['shiftcipher'] = array(
        'title' => 'Shift Cipher',
        'page callback' => 'drupal_get_form',
        'page arguments' => array('shiftcipher_form'),
        'access callback' => TRUE,
        'type' => MENU_NORMAL_ITEM,
    );
    $items['encoded_success_page'] = array(
      'title' => 'Encoded Message',
      'page callback' => 'encode_success',
      'access callback' => TRUE,
      'type' => MENU_CALLBACK,
    );
    return $items;
}
function shiftcipher_form(){
    $form['shiftvalue'] = array(
        '#title' => 'Shift Value',
        '#description' => "Enter the number of places you'd like your phrase to shift.",
        '#type' => 'textfield',
        '#element_validate' => array('element_validate_integer_positive'),
        '#required' => TRUE,
    );
    $form['direction'] = array(
        '#title' => 'Direction',
        '#description' => "Enter the direction you'd like your phrase to shift.",
        '#type' => 'textfield',
        '#element_validate' => array('element_validate_direction'),
        '#required' => TRUE,
    );
    $form['phrase'] = array(
        '#title' => 'Phrase',
        '#description' => "Enter the phrase you'd like turned into a cipher.",
        '#type' => 'textfield',
        '#element_validate' => array('element_validate_phrase'),
        '#required' => TRUE,
    );
    $form['submit'] = array(
        '#type' => 'submit',
        '#value' => 'Go',
    );
    return $form;
}
function element_validate_direction($element){
    if (((strtolower($element['#value']) != 'right')  && (strtolower($element['#value']) != 'left'))){
        form_error($element, t('You must either put "left" or "right" for the direction.'));
    }
}
function element_validate_phrase($element){
    $result = preg_match("/[@#^~``*&+[]/",$element['#value'], $matches);
    if ($result > 0){
        form_error($element, t('You must enter a valid sentence with proper punctuation.'));
    }
}
function shiftcipher_form_submit($form, &$form_state){
    $dictionary = 'abcdefghijklmnopqrstuvwxyz';
    $dictionary2 = 'zyxwvutsrqponmlkjihgfedcba';

    $_SESSION['phrase'] = "";
    $phrase = $form_state['values']['phrase'];
    if($form_state['values']['direction'] === 'left'){
        for ($i = 0, $length = strlen($phrase); $i < $length; $i++){
            $position = strpos($dictionary, $phrase[$i]) - $form_state['values']['shiftvalue'];
            if ($position < 0){
                $_SESSION['phrase'] .= $dictionary2[abs($position) - 1];
            } else {
                $_SESSION['phrase'] .= $dictionary[$position];
            }
            $form_state['redirect'] = 'encoded_success_page';
        }
    } else {
      for ($i = 0, $length = strlen($phrase); $i < $length; $i++){
          $position = strpos($dictionary, $phrase[$i]) + $form_state['values']['shiftvalue'];
          if ($position > 25){
              $new_position = ($position % 26);
              $_SESSION['phrase'] .= $dictionary[$new_position];
          } else {
              $_SESSION['phrase'] .= $dictionary[$position];
          }
          $form_state['redirect'] = 'encoded_success_page';
      }
    }
    // if($form_state['values']['direction'] === 'right'){
    //   foreach(str_split($phrase) as $character){
    //     $_SESSION['phrase'] .= chr(ord($character) + $form_state['values']['shiftvalue']);
    //   }
    // } else {
    //   foreach(str_split($phrase) as $character){
    //     $_SESSION['phrase'] .= chr(ord($character) - $form_state['values']['shiftvalue']);
    //   }
    // }
    // $form_state['redirect'] = 'encoded_success_page';
}
function encode_success(){
  return 'Here is your secret encoded message...' . $_SESSION['phrase'];
}
